### ISSUE TITLE
Performance issue with Sigma Dimensions

### ISSUE THREAD

**Issue by MiracleMagician** [Sigma88/Sigma-Dimensions#81]
The thing is, I've encountered a issue with performance, ~but unlike #72, it seems to be related to the resize, the larger I rescale to, the laggier.~ I'm using 4X resize on planet pack JNSQ, and I can only get 50 fps with a 40 part vessel on 640km sized minmus. The weirder thing is that I can get smooth 60 fps on a 6400km sized kerbin with 100 parts, which doesn't make any sense?
This bug seems to be present on 1.7.0 and 1.7.1, and regardless of what shader I'm using.
Sorry if I sound rude or something, for some reason I'm fairly bad at expressing politeness when using English. I absolutely love this mod and it has become one of my essential mods that I can't get rid of.

**Comment by Sigma88** [comment]
The reason why it is worse to have a 640km minmus than a 6400km kerbin is because most likely the game tries to load only a certain portion of the planet, since stock minmus is smaller the default is probably to load a big % of the planet (because it is so small anyways)

however, when you increase the size of minmus that big % keeps getting loaded all at once, which might be the cause of your FPS drop

I'm not really sure how to fix this, first of all I need to figure out which is the feature in question and then try to find a reasonable way to approach the solution

maybe @StollD knows which is the parameter in question

**Comment by Sigma88** [comment]
Just to be on the safe side, could you send me the files listed here:
https://forum.kerbalspaceprogram.com/index.php?/topic/181547-171-5-backports-kopernicus-kittopiatech/&page=27&tab=comments#comment-2793409

Thanks

**Comment by MiracleMagician** [comment]
I don't know how did I came to the conclusion that scale has a influence, probably because vsync was on and I got 60 FPS for a while in 1.1X resize. I moved almost all my mod away, disabled vsync, and get 110-130 FPS without Sigma dimensions, and 60-70 with it.
[Log stuff.zip](https://github.com/Sigma88/Sigma-Dimensions/files/3280616/Log.stuff.zip)
I also forgot to emphasize that I'm using planet pack JNSQ which compeletly overhauls all the planets, and is also a native 2.7X sized pack (So by scaling 4X the size will be 10.8X, aka real world size), so Kerbin and Minmus has different ground features than stock.

**Comment by Sigma88** [comment]
Did you try doing the test on just stock ksp to make sure it's not a jnsq issue?

**Comment by MiracleMagician** [comment]
UH oh, looks like a problem with JNSQ...
10X stock resize:
![screenshot3](https://user-images.githubusercontent.com/50024118/59348439-b167a700-8d49-11e9-8766-8ba703465c89.png)
Stock with only Kopernicus and its dependencies
![screenshot4](https://user-images.githubusercontent.com/50024118/59348470-c80dfe00-8d49-11e9-8e9d-1c7f9a2712e8.png)

**Comment by MiracleMagician** [comment]
HMMMMMM...
Default parameter doesn't slow down the game with JNSQ
![screenshot5](https://user-images.githubusercontent.com/50024118/59348863-d3adf480-8d4a-11e9-8e04-89af0fad6260.png)

**Comment by MiracleMagician** [comment]
OOF
After literally pressing F5 then F9, FPS drops down to 75
![screenshot6](https://user-images.githubusercontent.com/50024118/59349071-559e1d80-8d4b-11e9-8210-13f1dd3c9c27.png)

**Comment by MiracleMagician** [comment]
However save and load doesn't lag stock game with only Kopernicus and default parameter SD
Before:
![screenshot7](https://user-images.githubusercontent.com/50024118/59349460-4bc8ea00-8d4c-11e9-8926-5931058c46c3.png)
After:
![screenshot8](https://user-images.githubusercontent.com/50024118/59349467-4ff50780-8d4c-11e9-959f-665d9a6c0dee.png)

**Comment by MiracleMagician** [comment]
I think I can confirm this issue happens is related to SD, and only happens when a vessel is reloaded, since I smashed F5 and F9 a lot with a non SD install, with both JNSQ installed and not installed, but I can't notice any performance difference before and after loading a save in flight.

**Comment by MiracleMagician** [comment]
"I don't know how did I came to the conclusion that scale has a influence, probably because vsync was on and I got 60 FPS for a while in 1.1X resize. I moved almost all my mod away, disabled vsync, and get 110-130 FPS without Sigma dimensions, and 60-70 with it."
Regarding this, I think I didn't noticed performance issue only happens after loading a save in flight, so I came to the conclusion that it it related to planet size, but I think it's actually really an Sigma Dimension glitch.

**Comment by Sigma88** [comment]
I'm not really sure what the issue is,

from your screenshot there doesn't seem to be any difference between stock and 10x 

![image](https://user-images.githubusercontent.com/12640834/59356090-730dc000-8d28-11e9-8a89-1c54e1aae017.png)

on a 10x rescaled system (top) the framerate goes up and down between ~60 and ~190 while on stock it goes up and down between ~70 and ~170

am I missing something?

**Comment by Sigma88** [comment]
Here is a recompiled version of SD with a couple of features disabled, let's see if this has any effect

[SigmaDimensions.TEST_1.zip](https://github.com/Sigma88/Sigma-Dimensions/files/3281661/SigmaDimensions.TEST_1.zip)

I haven't tested this so it might not work properly 100%

of course don't use this on an important save, most likely hell will ensue

**Comment by MiracleMagician** [comment]
Whoops, I meant that game's performance only drops when reload a save on flight scene with sigma dimensions, previously I didn't notice that and performance issue wasn't there.

**Comment by MiracleMagician** [comment]
Whoops, I meant that game's performance only drops when reload a save on flight scene with sigma dimensions, previously I didn't notice that and performance issue wasn't there.

**Comment by MiracleMagician** [comment]
Oh, I think my English is just not that great. I meant see the posts below, not the screenshots

**Comment by MiracleMagician** [comment]
![screenshot13](https://user-images.githubusercontent.com/50024118/59358610-783a3180-8d5f-11e9-8de9-6ce712ffcb17.png)
uh oh

**Comment by Sigma88** [comment]
I understand what you mean, however I don't see much drop in the screenshot that's why I am a bit confused.

the logs are clean so there are no errors apparently, I'm not really sure how to approach this and I can't really reproduce the issue since my potato pc never goes over 70 fps 🤣

**Comment by Sigma88** [comment]
here
[SigmaDimensions.TEST_2.zip](https://github.com/Sigma88/Sigma-Dimensions/files/3281762/SigmaDimensions.TEST_2.zip)

also:
locate and delete the file `GameData\Sigma\Dimensions\Configs\ReDimension\resizePQSMods.cfg`

**Comment by MiracleMagician** [comment]
```
[LOG 22:15:50]: Parsing Target Mods in (Kopernicus.Configuration.PQSLoader) as (System.Collections.Generic.List`1[Kopernicus.Configuration.ModLoader.IModLoader])
[LOG 22:15:50]: Exception Was Recorded: Argument cannot be null.
Parameter name: type
  at System.Activator.CheckType (System.Type type) [0x00000] in <filename unknown>:0 
  at System.Activator.CreateInstance (System.Type type, Boolean nonPublic) [0x00000] in <filename unknown>:0 
  at System.Activator.CreateInstance (System.Type type) [0x00000] in <filename unknown>:0 
  at Kopernicus.ConfigParser.Parser.LoadCollectionMemberFromConfigurationNode (System.Reflection.MemberInfo member, System.Object o, .ConfigNode node, System.String configName, Boolean getChildren) [0x00000] in <filename unknown>:0 
  at Kopernicus.ConfigParser.Parser.LoadObjectFromConfigurationNode (System.Object o, .ConfigNode node, System.String configName, Boolean getChildren) [0x00000] in <filename unknown>:0 
  at Kopernicus.ConfigParser.Parser.LoadObjectMemberFromConfigurationNode (System.Reflection.MemberInfo member, System.Object o, .ConfigNode node, System.String configName, Boolean getChildren) [0x00000] in <filename unknown>:0 
  at Kopernicus.ConfigParser.Parser.LoadObjectFromConfigurationNode (System.Object o, .ConfigNode node, System.String configName, Boolean getChildren) [0x00000] in <filename unknown>:0 
  at Kopernicus.Configuration.Loader.Kopernicus.ConfigParser.Interfaces.IParserEventSubscriber.PostApply (.ConfigNode node) [0x00000] in <filename unknown>:0
``` 
`[LOG 22:15:50]: [Kopernicus]: Configuration.Loader: Failed to load Body: Squad/Moho: Argument cannot be null.`
BTW this is exceptions from Moho.Body.log and Kopernicus.log. Maybe this would provide a little help?

**Comment by MiracleMagician** [comment]
I still gets only ~75 fps rather than 130 on JNSQ's minmus surface, so I guess things aren't related to the parts that you removed?

**Comment by Sigma88** [comment]
is [this](https://github.com/Sigma88/Sigma-Dimensions/issues/81#issuecomment-501299032) even if you removed the cfg file I told you to?

**Comment by MiracleMagician** [comment]
Yes

**Comment by Sigma88** [comment]
and you don't get the error without SD

**Comment by MiracleMagician** [comment]
Yes...

**Comment by MiracleMagician** [comment]
I'll try remove SD and test again to 100% confirm this

**Comment by Sigma88** [comment]
thanks

**Comment by MiracleMagician** [comment]
BTW switching vessel/load a vessel from tracking station his the performance too, just discovered

**Comment by Sigma88** [comment]
>btw if you prefere I am also on kopernicus discord (channel "sigma-mods")
(I repeat this in case you missed it before)

could you try running the game with no plugin?

and this file still deleted
```GameData\Sigma\Dimensions\Configs\ReDimension\resizePQSMods.cfg```

**Comment by MiracleMagician** [comment]
I can confirm removing SD really removes the glitch, now it's time to test with only .cfg files
Actually I haven't used discord before... Maybe I'll look into that later?

**Comment by Sigma88** [comment]
>Actually I haven't used discord before... Maybe I'll look into that later?

don't worry we can speak here, it's just a weird type of chat 🤣

**Comment by Sigma88** [comment]
>I can confirm removing SD really removes the glitch, now it's time to test with only .cfg files

this is good

**Comment by MiracleMagician** [comment]
With only cfg files there's no fps drop

**Comment by Sigma88** [comment]
>With only cfg files there's no fps drop
ok, this is good news

**Comment by MiracleMagician** [comment]
And I noticed game seems to load faster between the scenes without SD, or is it only my illusion?

**Comment by MiracleMagician** [comment]
My discord stuck at checking updates... Maybe it's banned in China... Oof

**Comment by Sigma88** [comment]
here, try this one

[SigmaDimensions.TEST_3.zip](https://github.com/Sigma88/Sigma-Dimensions/files/3281906/SigmaDimensions.TEST_3.zip)

**Comment by MiracleMagician** [comment]
~75FPS

**Comment by Sigma88** [comment]
wtf :D

try this

[SigmaDimensions.TEST_4.zip](https://github.com/Sigma88/Sigma-Dimensions/files/3281942/SigmaDimensions.TEST_4.zip)

**Comment by MiracleMagician** [comment]
Discord isn't banned, it's just slow... extremely slow... And it isn't willing to connect via VPN for some reason

**Comment by Sigma88** [comment]
don't worry, chatting here is fine for me

**Comment by MiracleMagician** [comment]
Ahhh, I'll gonna say wtf too, it's still ~75FPS

**Comment by Sigma88** [comment]
>Ahhh, I'll gonna say wtf too, it's still ~75FPS

it is good, it means I can exclude everything I removed until now

here's the next step 
[SigmaDimensions.TEST_5.zip](https://github.com/Sigma88/Sigma-Dimensions/files/3281976/SigmaDimensions.TEST_5.zip)

**Comment by Sigma88** [comment]
sorry to waste your time with this, but I can't reproduce on my pc so the only way is to get feedback from players

**Comment by MiracleMagician** [comment]
~75FPS
Actually I want to say sorry too, I need to go sleep soon or I wont be able to get up tomorrow. After about 10 hours I'll have some time again.
I'm okay with testing your mods though, since I have an extra screen connected to my laptop I can watch some videos while testing KSP. And SD is one of my must-have mods, I'm glad I can help with its development.

**Comment by Sigma88** [comment]
I'll keep posting zips here, when you need to go just stop replying and when you have time we take from where we left off

[SigmaDimensions.TEST_6.zip](https://github.com/Sigma88/Sigma-Dimensions/files/3282031/SigmaDimensions.TEST_6.zip)

**Comment by Sigma88** [comment]
if TEST_6 still has issues here is TEST_7
[SigmaDimensions.TEST_7.zip](https://github.com/Sigma88/Sigma-Dimensions/files/3282040/SigmaDimensions.TEST_7.zip)

**Comment by Sigma88** [comment]
and if 7 doesn't fix, here's 8
[SigmaDimensions.TEST_8.zip](https://github.com/Sigma88/Sigma-Dimensions/files/3282046/SigmaDimensions.TEST_8.zip)

**Comment by MiracleMagician** [comment]
~130 FPS on 6!

**Comment by MiracleMagician** [comment]
To make sure it's the module removed on 6 is the cause of the glitch, I tested again and get ~70 on 5, 130 on 7 and 8

**Comment by Sigma88** [comment]
Yes I had a feeling 6 was the solution

**Comment by Sigma88** [comment]
This should be fairly easy to fix

**Comment by MiracleMagician** [comment]
Nice

**Comment by Sigma88** [comment]
here's another test version:
[SigmaDimensions.TEST_9.zip](https://github.com/Sigma88/Sigma-Dimensions/files/3288244/SigmaDimensions.TEST_9.zip)

before to install this:

1- remove the old SigmaDimensions folder and re-install the mod properly
2- replace the SD dll with the test_10 dll
3- test if the bug has been fixed

**Comment by MiracleMagician** [comment]
Weird. Instead of 75 or 130 fps I get ~95 this time.

**Comment by Sigma88** [comment]
I was worried this could happen, there might be 2 problems. we need to figure out which is the second part that is causing the fps drop.

here is a new dll to test
[SigmaDimensions.TEST_10.zip](https://github.com/Sigma88/Sigma-Dimensions/files/3289697/SigmaDimensions.TEST_10.zip)


alternatively, this could be an issue related to terrain scatter ([see this kopernicus issue](https://github.com/Kopernicus/Kopernicus/issues/365))
so please try also to load the game with SD TEST_9 and disabling terrain scatter in the settings

**Comment by MiracleMagician** [comment]
Maybe not related to that issue, since my terrain scatter is already disabled, and got same performance problem before switching to 1.7.1.
Test 10 improves the game performance a bit more, but I still seems to have 5-10 fps lower without SD.
That's acceptable though, I think I can land a 200 part vessel on minmus now...

**Comment by Sigma88** [comment]
could you try this version?
[SigmaDimensions.TEST_11.zip](https://github.com/Sigma88/Sigma-Dimensions/files/3290946/SigmaDimensions.TEST_11.zip)

**Comment by MiracleMagician** [comment]
Whoops, was writing my assignment and didn't notice your comment until now. Guess I'll give it a test tomorrow (about 8 hours later)...

**Comment by Sigma88** [comment]
Don't worry, I may be able to upload a couple of more tests by then

**Comment by MiracleMagician** [comment]
11 seems to have no improvent for me

**Comment by Sigma88** [comment]
do you mean improvement over the current release or over TEST_10 ?

it should not improve on 10,

TEST_10 had 2 features disabled

TEST_11 has 1 feature disabled and 1 feature fixed

if you are getting the same FPS with TEST_10 as you get with TEST_11 that's a good thing

**Comment by MiracleMagician** [comment]
Yep, almost the same FPS.👍

**Comment by Sigma88** [comment]
Ok, this is a good sign then!

**Comment by Sigma88** [comment]
here, this should be a version of the current SD that have the fps drop fixed
[SigmaDimensions.TEST_12.zip](https://github.com/Sigma88/Sigma-Dimensions/files/3293641/SigmaDimensions.TEST_12.zip)

while I was fixing this I found some bugs that are present in this version but are also in the latest release.
since Test_12 fixes this issue you can just use this and I will try fixing the other bugs before making a new release.

let me know if this version gives you any issues

thanks for helping fixing this issue!

**Comment by MiracleMagician** [comment]
Seems this bug is fixed for me!

**Comment by Sigma88** [comment]
I'm going to release this in a few days.
I will leave it here in case someone wants to test it first

The only changes from the latest release are the performance drop fix linked above and another fix for building altitude recalculation

[SigmaDimensions.TEST_13.zip](https://github.com/Sigma88/Sigma-Dimensions/files/3298923/SigmaDimensions.TEST_13.zip)

**Comment by Sigma88** [comment]
fixed in the latest release

https://github.com/Sigma88/Sigma-Dimensions/releases/v0.10.4

**Comment by gazpachian** [comment]
This bug persists for me (perhaps due to different issues) in KSP/Kopernicus version 1.8.1 with SD 0.10.7 under Linux. I ran the game fine at ~2x scale, stock system, with a decently sized mod list for a couple of months, then decided to restart at a larger scale (4.3x) and I get massive performance hits when close to the surface of the Mun or Minmus. Especially at Minmus it is evident the terrain is loaded at a much higher detail than necessary for quite some distance - distant hills are visibly smoother than they "should be". 

Failed attempt at fixing the issue: MM patch to limit the max PQS detail seems to have no discernible effect on performance:

@Kopernicus:FOR[SigDim2]
{
    @Body:HAS[@PQS]
	{
		@PQS
		{
			%minLevel = 1
			%maxLevel = 4
		}
	}
}

With the issue also mentioned in relation to JNSQ by ArXen42 I assume the likely culprit is Kopernicus itself this time? Still I figure the issue is likely highly related to the original issue in SD, so perhaps you recall what you changed in SD to fix this originally and see if any related issues have popped up in the source for Kopernicus in later iterations?

**Comment by Sigma88** [comment]
yes I am supposed to change the min/max level  but I haven't had too much free time lately and honestly ksp modding is not very high on my priority list at the moment

**Comment by gazpachian** [comment]
No worries, thanks for taking the time to reply and hope you're doing well!
